services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: metube
    volumes:
      - ./db-data/var/lib/postgres/data


  channel-service:
    image: channel-service
    build: ./
    ports:
      - "8085:8085"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 1234

